baseurl = "https://darwinleung.github.io/"
languageCode = "en-us"
title = "DL"
theme = "hyde"

[params]
    description = "Darwin Leung's personal blog"
    copyright = "Built with Hugo and Hyde ©2018. All rights reserved."
    themeColor = "theme-base-0g" # for hyde theme